/*
 * Some options to inspect how APT solves the problem of satisfying
 * dependencies by package installations/removals.
 *
 * Uncomment below to diagnose package installation/upgrade problems.
 */

/* The common diagnostics (asked for in bug reports). */
// Debug::pkgMarkInstall "true";
// Debug::pkgProblemResolver "true";

/* Even more detailed inspection, but too noisy (since 0.5.15lorg2-alt83). */
// Debug::pkgMark-shallow "true";
// Debug::pkgMark-allcalls "true";
