/*
 * Some options to inspect how APT fetches files and talks to remote hosts.
 */

// Acquire::Verbose "true";
// Debug::pkgAcquire::Auth "true";

// Debug::identcdrom "true";

// Debug::Acquire::http "true";

/* A directory where to log connection operations and the data sent/recvd
   (since 0.5.15lorg2-alt90). Enabled if the value is not empty. */
// Debug::Connect "/some/place/for/logs";
