/* Some UI options for APT commands; uncomment to change their appearance. */

/* Columnar output for package lists similar to 'ls' (experimental,
   since 0.5.15lorg2-alt88, by default: on; uncomment to turn it off).
*/
// APT::Get::List-Columns "false";
