#!/bin/bash
set -eu

TESTDIR=$(readlink -f $(dirname $0))

case "$APT_TEST_METHOD" in
	https|https_*)
		:
		;;
	*)
		echo 'SKIP (makes sense only for APT_TEST_METHOD being https*)' >&2
		exit 0
		;;
esac

. $TESTDIR/framework-without-repo
prereq $TESTDIR/test-apt-install-simple

# Generate another key, and pin apt to it. Check cert pinning

# use a filename which is unique for this specific test (not to interfere)
mk_intermediate cert/"${0##*/}"@"$NGINX_HOST"/crt \
		ssl_keygen

msgmsg 'Pinning invalid cert in apt'
cat >| "$APT_TEST_PINNING_CONF" <<- END
Acquire::https::PinnedCert	"$APT_TEST_INTERMEDIATES/cert/${0##*/}@$NGINX_HOST/crt";
END

testfailure aptget update

testpkgnotinstalled 'conflicting-package-one'
testfailure aptget install conflicting-package-one
testpkgnotinstalled 'conflicting-package-one'

msgmsg 'Pinning the valid cert in apt'
cat >| "$APT_TEST_PINNING_CONF" <<- END
Acquire::https::PinnedCert	"$NGINX_CRT";
END

testsuccess aptget update

testpkgnotinstalled 'conflicting-package-one'
testsuccess aptget install conflicting-package-one
testpkginstalled 'conflicting-package-one'
