#!/bin/bash
set -eu

TESTDIR=$(readlink -f $(dirname $0))
. $TESTDIR/framework

APT_TEST_XFAIL=yes

setupenvironment

buildpackage 'large-package'

generaterepository_and_switch_sources "$TMPWORKINGDIRECTORY/usr/src/RPM/RPMS"

testsuccess aptget update

testpkgnotinstalled 'large-package'
testsuccess aptget install large-package
testpkginstalled 'large-package'
