#!/bin/bash
set -eu

TESTDIR=$(readlink -f $(dirname $0))

. $TESTDIR/framework-without-repo
prereq $TESTDIR/try-apt-method-http-when-allowed-only-proxy

# use the saved value
msgmsg "Setting proxy for http in apt in config: $APT_TEST_HTTP_PROXY"
cat > "$APT_TEST_PROXY_FOR_HTTP_CONF" <<- END
Acquire::http::Proxy	"$APT_TEST_HTTP_PROXY";
END

testsuccess aptget update

testpkgnotinstalled 'simple-package'
testsuccess aptget install 'simple-package'
testpkginstalled 'simple-package'
