#!/bin/bash
set -eu

TESTDIR=$(readlink -f $(dirname $0))
. $TESTDIR/framework

setupenvironment

buildpackage 'simple-package'

readonly P=simple-package-update
readonly N=$(( 1024 + 100 ))
build_P()
{
    local -r i="$1"; shift
    local name
    printf -v name '%s-%04x' "$P" "$i"

    local -r trap_before_mkdir="$CURRENTTRAP"

    # where the spec is being generated and/or cached:
    local -r d="$APT_TEST_INTERMEDIATES/specs/$name"
    mkdir -p "${d%/*}"
    if ! mkdir "$d" &>/dev/null; then
	msginfo "Re-using generated spec: ${name}"
	wait_for_file "$d"/spec
    else

	# After an error during the procedure here, we have to delete the dir
	# in order to make clear that one shouldn't start waiting for a result
	# on the other branch. So we push a temporary trap for this.
	# (Then restore from $trap_before_mkdir. Not so important since build_P
	# is always run in a subshell, but this way it's more consistent.)
	# (And waiting that has already started can be limited in wait_for_file.)
	# Note: This doesn't prevent trying the erroneous procedure once again.
	addtrap prefix 'rm -rf %q' "$d"

	msginfo "Generating spec: ${name}"

	local in_spec="$APT_TEST_INTERMEDIATES/specs/$P"/spec
	if ! [ -e "$in_spec" ]; then
	    in_spec="${TESTDIRECTORY}/specs/${P}.spec"
	fi
	local -r in_spec
	if ! [ -e "$in_spec" ]; then
	    msgdie "No spec for $P found in {APT_TEST_INTERMEDIATES,TESTDIRECTORY}/specs/"
	fi

	# Instead of editing the spec-file, we could perhaps use rpmbuild --define.
	sed -E \
	    -e 's/^Version:[[:space:]]* 2$/'"Version: $i/" \
	    -e 's/ 2-alt1$/'" $i-alt1/" \
	    <"$in_spec" \
	    >|"$d"/spec.in-progress
	mv -T "$d"/spec{.in-progress,}

	CURRENTTRAP="$trap_before_mkdir"
	addtrap ''

    fi

    buildpackage "$name"
}

if [ -z "${PARALLEL_SLOT-}" ]; then
    # We are not run in parallel under xargs,
    # so we can use parallelism for a speed-up here.
    NPROC="$(nproc)"
    readonly NPROC
    busy=0
    for (( I=2; I <= N; ++I )); do
	if (( ++busy > NPROC )); then
	    wait -n
	    (( --busy )) ||:
	fi
	{ CURRENTTRAP=; build_P "$I"; } &
    done
else
    # Do not use parallelism inside parallelism,
    # otherwise fork would become unavailable.
    for (( I=2; I <= N; ++I )); do
	(CURRENTTRAP=; build_P "$I"); [ 0 -eq $? ] # bash3 workaround
    done
fi

buildpackage 'conflicting-package-one'
buildpackage 'conflicting-package-distupgrade'

testpkgnotinstalled 'simple-package'
testpkgnotinstalled 'conflicting-package-one'
aptgetinstallpackage 'simple-package'
aptgetinstallpackage 'conflicting-package-one'
testpkginstalled 'simple-package'
testpkginstalled 'conflicting-package-one'

testequal '1-alt1' getpackageversion 'simple-package'
testequal '1-alt1' getpackageversion 'conflicting-package-one'

wait # we don't care much whether a few (up to 99) of the build_P's failed
generaterepository_and_switch_sources "$TMPWORKINGDIRECTORY/usr/src/RPM/RPMS"

testsuccess aptget update

# At least, it fails on assertion instead of badly overflowing the buffer.
testregexmatch '.*: Assertion .* failed\.
' \
	       aptget dist-upgrade -y
testfailure

# More correct behavior would be:
#testsuccess aptget dist-upgrade -y
#testequal "$N-alt1" getpackageversion 'simple-package'
#testequal '1-alt1' getpackageversion 'conflicting-package-one'
