#!/bin/bash
set -eu

case "$APT_TEST_METHOD" in
	https|https_*)
		:
		;;
	*)
		echo 'SKIP (makes sense only for APT_TEST_METHOD being https*)' >&2
		exit 0
		;;
esac

TESTDIR=$(readlink -f $(dirname $0))

. $TESTDIR/framework-without-repo
prereq $TESTDIR/try-method-http-when-allowed-only-proxy

# use the saved value
msgmsg "Setting proxy for https in apt in config: $APT_TEST_HTTP_PROXY"
cat > "$APT_TEST_PROXY_FOR_HTTP_CONF" <<- END
Acquire::https::Proxy	"$APT_TEST_HTTP_PROXY";
END

# Acquire::https::Proxy is not honored by apt, just Acquire::http::Proxy.
case "$APT_TEST_METHOD" in
    http*_localhost6*)
	echo 'SKIP on IPv6, shows nothing (direct access is not denied; Acquire::https::Proxy is not used)' >&2
	exit 0
	;;
esac
APT_TEST_XFAIL=yes

testsuccess aptget update

testpkgnotinstalled 'simple-package'
testsuccess aptget install 'simple-package'
testpkginstalled 'simple-package'
