#!/bin/bash
set -eu

TESTDIR=$(readlink -f $(dirname $0))

case "$APT_TEST_METHOD" in
	https|https_*)
		:
		;;
	*)
		echo 'SKIP (makes sense only for APT_TEST_METHOD being https*)' >&2
		exit 0
		;;
esac

. $TESTDIR/framework-without-repo
prereq $TESTDIR/test-apt-install-simple

# Generate another key, and pin apt to it. Check cert pinning

# use a filename which is unique for this specific test (not to interfere)
readonly MY_OTHER_CRT=$TMPWORKINGDIRECTORY/cert."${0##*/}".crt
openssl req -x509 \
	-newkey rsa:4096 \
	-keyout /dev/null \
	-out "$MY_OTHER_CRT" \
	-nodes \
	-days 365 \
	-subj "/CN=$NGINX_HOST" \
    &>/dev/null

msgmsg 'Pinning invalid cert in apt'
cat >| "$APT_TEST_PINNING_CONF" <<- END
Acquire::https::PinnedCert	"$MY_OTHER_CRT";
END

testfailure aptget update

testpkgnotinstalled 'conflicting-package-one'
testfailure aptget install conflicting-package-one
testpkgnotinstalled 'conflicting-package-one'

msgmsg 'Pinning the valid cert in apt'
cat >| "$APT_TEST_PINNING_CONF" <<- END
Acquire::https::PinnedCert	"$NGINX_CRT";
END

testsuccess aptget update

testpkgnotinstalled 'conflicting-package-one'
testsuccess aptget install conflicting-package-one
testpkginstalled 'conflicting-package-one'
